import Head from 'next/head'

function about(){
    return <>
    <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>       
        <h1>About</h1>
    </>
}

export default about